/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, Gun, User } from "@prisma/client";

export class GunServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.GunFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.GunFindManyArgs>
  ): Promise<number> {
    return this.prisma.gun.count(args);
  }

  async findMany<T extends Prisma.GunFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.GunFindManyArgs>
  ): Promise<Gun[]> {
    return this.prisma.gun.findMany(args);
  }
  async findOne<T extends Prisma.GunFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.GunFindUniqueArgs>
  ): Promise<Gun | null> {
    return this.prisma.gun.findUnique(args);
  }
  async create<T extends Prisma.GunCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.GunCreateArgs>
  ): Promise<Gun> {
    return this.prisma.gun.create<T>(args);
  }
  async update<T extends Prisma.GunUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.GunUpdateArgs>
  ): Promise<Gun> {
    return this.prisma.gun.update<T>(args);
  }
  async delete<T extends Prisma.GunDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.GunDeleteArgs>
  ): Promise<Gun> {
    return this.prisma.gun.delete(args);
  }

  async getMessage(parentId: string): Promise<User | null> {
    return this.prisma.gun
      .findUnique({
        where: { id: parentId },
      })
      .message();
  }
}
