/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateGunArgs } from "./CreateGunArgs";
import { UpdateGunArgs } from "./UpdateGunArgs";
import { DeleteGunArgs } from "./DeleteGunArgs";
import { GunFindManyArgs } from "./GunFindManyArgs";
import { GunFindUniqueArgs } from "./GunFindUniqueArgs";
import { Gun } from "./Gun";
import { GunService } from "../gun.service";

@graphql.Resolver(() => Gun)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class GunResolverBase {
  constructor(
    protected readonly service: GunService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Gun",
    action: "read",
    possession: "any",
  })
  async _gunsMeta(
    @graphql.Args() args: GunFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Gun])
  @nestAccessControl.UseRoles({
    resource: "Gun",
    action: "read",
    possession: "any",
  })
  async guns(
    @graphql.Args() args: GunFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Gun[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Gun",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Gun, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Gun",
    action: "read",
    possession: "own",
  })
  async gun(
    @graphql.Args() args: GunFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Gun | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Gun",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Gun)
  @nestAccessControl.UseRoles({
    resource: "Gun",
    action: "create",
    possession: "any",
  })
  async createGun(
    @graphql.Args() args: CreateGunArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Gun> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Gun",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Gun"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Gun)
  @nestAccessControl.UseRoles({
    resource: "Gun",
    action: "update",
    possession: "any",
  })
  async updateGun(
    @graphql.Args() args: UpdateGunArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Gun | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Gun",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Gun"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Gun)
  @nestAccessControl.UseRoles({
    resource: "Gun",
    action: "delete",
    possession: "any",
  })
  async deleteGun(@graphql.Args() args: DeleteGunArgs): Promise<Gun | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
